/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.scoping;

import uk.kcl.ac.inf.jsonlang.scoping.AbstractJSONLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class JSONLanguageScopeProvider extends AbstractJSONLanguageScopeProvider {
}
