/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang;

import uk.kcl.ac.inf.jsonlang.AbstractJSONLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class JSONLanguageRuntimeModule extends AbstractJSONLanguageRuntimeModule {
}
