/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang;

import uk.kcl.ac.inf.jsonlang.JSONLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class JSONLanguageStandaloneSetup extends JSONLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new JSONLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
