/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jsonLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.ComplexNumber#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonLanguagePackage#getComplexNumber()
 * @model
 * @generated
 */
public interface ComplexNumber extends uk.kcl.ac.inf.jsonlang.jsonLanguage.Number
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(float)
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonLanguagePackage#getComplexNumber_Val()
   * @model
   * @generated
   */
  float getVal();

  /**
   * Sets the value of the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.ComplexNumber#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(float value);

} // ComplexNumber
