/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jSONLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface JSONLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jSONLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.kcl.uk/ac/inf/jsonlang/JSONLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jSONLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JSONLanguagePackage eINSTANCE = uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ValueImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getValue()
   * @generated
   */
  int VALUE = 2;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.jSONLanguageImpl <em>jSON Language</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.jSONLanguageImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getjSONLanguage()
   * @generated
   */
  int JSON_LANGUAGE = 0;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_LANGUAGE__STATEMENT = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>jSON Language</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_LANGUAGE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.StatementImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ArrayImpl <em>Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ArrayImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getArray()
   * @generated
   */
  int ARRAY = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY__VALUE = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.TextImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getText()
   * @generated
   */
  int TEXT = 4;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.BooleanImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 5;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.NullImpl <em>Null</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.NullImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getNull()
   * @generated
   */
  int NULL = 6;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NULL__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Null</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NULL_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.NumberImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 7;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.IntNumberImpl <em>Int Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.IntNumberImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getIntNumber()
   * @generated
   */
  int INT_NUMBER = 8;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_NUMBER__VAL = NUMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_NUMBER_FEATURE_COUNT = NUMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ComplexNumberImpl <em>Complex Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ComplexNumberImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getComplexNumber()
   * @generated
   */
  int COMPLEX_NUMBER = 9;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_NUMBER__VAL = NUMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Complex Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_NUMBER_FEATURE_COUNT = NUMBER_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage <em>jSON Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>jSON Language</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage
   * @generated
   */
  EClass getjSONLanguage();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statement</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage#getStatement()
   * @see #getjSONLanguage()
   * @generated
   */
  EReference getjSONLanguage_Statement();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getKey()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Key();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getValue()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Value();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Array <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Array
   * @generated
   */
  EClass getArray();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Array#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Array#getValue()
   * @see #getArray()
   * @generated
   */
  EReference getArray_Value();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Text#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Text#getVal()
   * @see #getText()
   * @generated
   */
  EAttribute getText_Val();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Boolean#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Boolean#getVal()
   * @see #getBoolean()
   * @generated
   */
  EAttribute getBoolean_Val();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Null <em>Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Null</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Null
   * @generated
   */
  EClass getNull();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Null#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Null#getVal()
   * @see #getNull()
   * @generated
   */
  EAttribute getNull_Val();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.IntNumber <em>Int Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Number</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.IntNumber
   * @generated
   */
  EClass getIntNumber();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.IntNumber#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.IntNumber#getVal()
   * @see #getIntNumber()
   * @generated
   */
  EAttribute getIntNumber_Val();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.ComplexNumber <em>Complex Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Number</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.ComplexNumber
   * @generated
   */
  EClass getComplexNumber();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.ComplexNumber#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.ComplexNumber#getVal()
   * @see #getComplexNumber()
   * @generated
   */
  EAttribute getComplexNumber_Val();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JSONLanguageFactory getJSONLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.jSONLanguageImpl <em>jSON Language</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.jSONLanguageImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getjSONLanguage()
     * @generated
     */
    EClass JSON_LANGUAGE = eINSTANCE.getjSONLanguage();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_LANGUAGE__STATEMENT = eINSTANCE.getjSONLanguage_Statement();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.StatementImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__KEY = eINSTANCE.getStatement_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__VALUE = eINSTANCE.getStatement_Value();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ValueImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ArrayImpl <em>Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ArrayImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getArray()
     * @generated
     */
    EClass ARRAY = eINSTANCE.getArray();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY__VALUE = eINSTANCE.getArray_Value();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.TextImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__VAL = eINSTANCE.getText_Val();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.BooleanImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__VAL = eINSTANCE.getBoolean_Val();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.NullImpl <em>Null</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.NullImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getNull()
     * @generated
     */
    EClass NULL = eINSTANCE.getNull();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NULL__VAL = eINSTANCE.getNull_Val();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.NumberImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.IntNumberImpl <em>Int Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.IntNumberImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getIntNumber()
     * @generated
     */
    EClass INT_NUMBER = eINSTANCE.getIntNumber();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_NUMBER__VAL = eINSTANCE.getIntNumber_Val();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ComplexNumberImpl <em>Complex Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ComplexNumberImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getComplexNumber()
     * @generated
     */
    EClass COMPLEX_NUMBER = eINSTANCE.getComplexNumber();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_NUMBER__VAL = eINSTANCE.getComplexNumber_Val();

  }

} //JSONLanguagePackage
