/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jsonLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface JsonLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jsonLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.kcl.uk/ac/inf/jsonlang/JsonLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jsonLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JsonLanguagePackage eINSTANCE = uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ValueImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getValue()
   * @generated
   */
  int VALUE = 2;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonProgramImpl <em>Json Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonProgramImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getJsonProgram()
   * @generated
   */
  int JSON_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_PROGRAM__STATEMENT = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_PROGRAM_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.StatementImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ArrayImpl <em>Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ArrayImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getArray()
   * @generated
   */
  int ARRAY = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY__VALUE = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.TextImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getText()
   * @generated
   */
  int TEXT = 4;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.BooleanImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 5;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.NullImpl <em>Null</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.NullImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getNull()
   * @generated
   */
  int NULL = 6;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NULL__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Null</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NULL_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.NumberImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 7;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.IntNumberImpl <em>Int Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.IntNumberImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getIntNumber()
   * @generated
   */
  int INT_NUMBER = 8;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_NUMBER__VAL = NUMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_NUMBER_FEATURE_COUNT = NUMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ComplexNumberImpl <em>Complex Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ComplexNumberImpl
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getComplexNumber()
   * @generated
   */
  int COMPLEX_NUMBER = 9;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_NUMBER__VAL = NUMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Complex Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_NUMBER_FEATURE_COUNT = NUMBER_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonProgram <em>Json Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Program</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonProgram
   * @generated
   */
  EClass getJsonProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonProgram#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statement</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonProgram#getStatement()
   * @see #getJsonProgram()
   * @generated
   */
  EReference getJsonProgram_Statement();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Statement#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Statement#getKey()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Key();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Statement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Statement#getValue()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Value();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Array <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Array
   * @generated
   */
  EClass getArray();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Array#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Array#getValue()
   * @see #getArray()
   * @generated
   */
  EReference getArray_Value();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Text#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Text#getVal()
   * @see #getText()
   * @generated
   */
  EAttribute getText_Val();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Boolean#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Boolean#getVal()
   * @see #getBoolean()
   * @generated
   */
  EAttribute getBoolean_Val();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Null <em>Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Null</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Null
   * @generated
   */
  EClass getNull();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Null#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Null#getVal()
   * @see #getNull()
   * @generated
   */
  EAttribute getNull_Val();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.IntNumber <em>Int Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Number</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.IntNumber
   * @generated
   */
  EClass getIntNumber();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.IntNumber#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.IntNumber#getVal()
   * @see #getIntNumber()
   * @generated
   */
  EAttribute getIntNumber_Val();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.ComplexNumber <em>Complex Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Number</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.ComplexNumber
   * @generated
   */
  EClass getComplexNumber();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.ComplexNumber#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.ComplexNumber#getVal()
   * @see #getComplexNumber()
   * @generated
   */
  EAttribute getComplexNumber_Val();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JsonLanguageFactory getJsonLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonProgramImpl <em>Json Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonProgramImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getJsonProgram()
     * @generated
     */
    EClass JSON_PROGRAM = eINSTANCE.getJsonProgram();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_PROGRAM__STATEMENT = eINSTANCE.getJsonProgram_Statement();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.StatementImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__KEY = eINSTANCE.getStatement_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__VALUE = eINSTANCE.getStatement_Value();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ValueImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ArrayImpl <em>Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ArrayImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getArray()
     * @generated
     */
    EClass ARRAY = eINSTANCE.getArray();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY__VALUE = eINSTANCE.getArray_Value();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.TextImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__VAL = eINSTANCE.getText_Val();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.BooleanImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__VAL = eINSTANCE.getBoolean_Val();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.NullImpl <em>Null</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.NullImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getNull()
     * @generated
     */
    EClass NULL = eINSTANCE.getNull();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NULL__VAL = eINSTANCE.getNull_Val();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.NumberImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.IntNumberImpl <em>Int Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.IntNumberImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getIntNumber()
     * @generated
     */
    EClass INT_NUMBER = eINSTANCE.getIntNumber();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_NUMBER__VAL = eINSTANCE.getIntNumber_Val();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ComplexNumberImpl <em>Complex Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.ComplexNumberImpl
     * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.impl.JsonLanguagePackageImpl#getComplexNumber()
     * @generated
     */
    EClass COMPLEX_NUMBER = eINSTANCE.getComplexNumber();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_NUMBER__VAL = eINSTANCE.getComplexNumber_Val();

  }

} //JsonLanguagePackage
