/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jSONLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>jSON Language</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguagePackage#getjSONLanguage()
 * @model
 * @generated
 */
public interface jSONLanguage extends Value
{
  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference list.
   * The list contents are of type {@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference list.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguagePackage#getjSONLanguage_Statement()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatement();

} // jSONLanguage
