/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jSONLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface JSONLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jSONLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.kcl.uk/ac/inf/jsonlang/JSONLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jSONLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JSONLanguagePackage eINSTANCE = uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ValueImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getValue()
   * @generated
   */
  int VALUE = 2;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.jSONLanguageImpl <em>jSON Language</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.jSONLanguageImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getjSONLanguage()
   * @generated
   */
  int JSON_LANGUAGE = 0;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_LANGUAGE__STATEMENT = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>jSON Language</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_LANGUAGE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.StatementImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ArrayImpl <em>Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ArrayImpl
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getArray()
   * @generated
   */
  int ARRAY = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY__VALUE = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage <em>jSON Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>jSON Language</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage
   * @generated
   */
  EClass getjSONLanguage();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statement</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage#getStatement()
   * @see #getjSONLanguage()
   * @generated
   */
  EReference getjSONLanguage_Statement();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getKey()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Key();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getValue()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Value();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Array <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Array
   * @generated
   */
  EClass getArray();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Array#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value</em>'.
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.Array#getValue()
   * @see #getArray()
   * @generated
   */
  EReference getArray_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JSONLanguageFactory getJSONLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.jSONLanguageImpl <em>jSON Language</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.jSONLanguageImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getjSONLanguage()
     * @generated
     */
    EClass JSON_LANGUAGE = eINSTANCE.getjSONLanguage();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_LANGUAGE__STATEMENT = eINSTANCE.getjSONLanguage_Statement();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.StatementImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__KEY = eINSTANCE.getStatement_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__VALUE = eINSTANCE.getStatement_Value();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ValueImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ArrayImpl <em>Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.ArrayImpl
     * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.impl.JSONLanguagePackageImpl#getArray()
     * @generated
     */
    EClass ARRAY = eINSTANCE.getArray();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY__VALUE = eINSTANCE.getArray_Value();

  }

} //JSONLanguagePackage
