/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jSONLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguagePackage#getNumber()
 * @model
 * @generated
 */
public interface Number extends Value
{
} // Number
