/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jSONLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getKey <em>Key</em>}</li>
 *   <li>{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguagePackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguagePackage#getStatement_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Value)
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguagePackage#getStatement_Value()
   * @model containment="true"
   * @generated
   */
  Value getValue();

  /**
   * Sets the value of the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Value value);

} // Statement
