/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jSONLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Text#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguagePackage#getText()
 * @model
 * @generated
 */
public interface Text extends Value
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(String)
   * @see uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguagePackage#getText_Val()
   * @model
   * @generated
   */
  String getVal();

  /**
   * Sets the value of the '{@link uk.kcl.ac.inf.jsonlang.jSONLanguage.Text#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(String value);

} // Text
