/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jsonLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonLanguagePackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
} // Value
