/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.kcl.ac.inf.jsonlang.ui.internal.JsonlangActivator;

public class JsonLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JsonlangActivator.getInstance().getInjector("uk.kcl.ac.inf.jsonlang.JsonLanguage");
	}

}
