/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ide;


/**
 * Use this class to register ide components.
 */
public class JSONLanguageIdeModule extends AbstractJSONLanguageIdeModule {
}
