/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.kcl.ac.inf.jsonlang.JSONLanguageRuntimeModule;
import uk.kcl.ac.inf.jsonlang.JSONLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JSONLanguageIdeSetup extends JSONLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JSONLanguageRuntimeModule(), new JSONLanguageIdeModule()));
	}
	
}
