/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class JSONLanguageUiModule extends AbstractJSONLanguageUiModule {
}
