/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JSONLanguageUiModule extends AbstractJSONLanguageUiModule {

	public JSONLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
