/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJsonLanguageScopeProvider extends DelegatingScopeProvider {
}
