/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uk.kcl.ac.inf.jsonlang.ui.AbstractJsonLanguageUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class JsonLanguageUiModule extends AbstractJsonLanguageUiModule {
  public JsonLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
