/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.validation

import org.eclipse.xtext.validation.Check
import uk.kcl.ac.inf.jsonlang.jsonLanguage.Statement
import uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonLanguagePackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class JsonLanguageValidator extends AbstractJsonLanguageValidator {
	
	public static val KEY_CONTAINS_NUMBER_AT_START = 'uk.kcl.ac.inf.jsonlang.KEY_CONTAINS_NUMBER_AT_START'
	public static val KEY_STARTS_WITH_CAPITAL = 'uk.kcl.ac.inf.jsonlang.KEY_STARTS_WITH_CAPITAL'
	public static val KEY_CONTAINS_SPACES = 'uk.kcl.ac.inf.jsonlang.KEY_CONTAINS_SPACES'

	@Check
	def CheckKeyDoesNotStartWithNumber(Statement statement) {
		if(Character.isDigit(statement.key.charAt(0))) {
			warning('Key should not start with a numerical character', statement,
				JsonLanguagePackage.Literals.STATEMENT__KEY,
				KEY_CONTAINS_NUMBER_AT_START
			)
		}
	}
	
	@Check
	def CheckKeyDoesNotStartWithCapital(Statement statement) {
		if(Character.isLetter(statement.key.charAt(0))) {
			if(!Character.isLowerCase(statement.key.charAt(0))) {
				warning('Key should not start with a capital letter', statement,
				JsonLanguagePackage.Literals.STATEMENT__KEY,
				KEY_STARTS_WITH_CAPITAL
				)
			}
		}
	}
	
	@Check
	def CheckKeyDoesNotContainSpaces(Statement statement) {
		if(statement.key.contains(" ")) {
			warning('Key should not contain spaces', statement,
				JsonLanguagePackage.Literals.STATEMENT__KEY,
				KEY_CONTAINS_SPACES
			)
		}
	}
	
}
