/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.validation

import org.eclipse.xtext.validation.Check
import uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement

/** 
 * This class contains custom validation rules. 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class JSONLanguageValidator extends AbstractJSONLanguageValidator {
	
	

	@Check
	def CheckKeyDoesNotStartWithNumber(Statement statement) {
		
	}
}
