/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ui.contentassist;

import uk.kcl.ac.inf.jsonlang.ui.contentassist.AbstractJsonLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class JsonLanguageProposalProvider extends AbstractJsonLanguageProposalProvider {
}
