/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import uk.kcl.ac.inf.jsonlang.tests.JSONLanguageInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(JSONLanguageInjectorProvider.class)
@SuppressWarnings("all")
public class JSONLanguageParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field JSONLanguageParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
