/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jSONLanguage.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import uk.kcl.ac.inf.jsonlang.jSONLanguage.Array;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.ComplexNumber;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.IntNumber;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguageFactory;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.JSONLanguagePackage;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.Null;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.Text;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.Value;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.jSONLanguage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class JSONLanguageFactoryImpl extends EFactoryImpl implements JSONLanguageFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static JSONLanguageFactory init()
  {
    try
    {
      JSONLanguageFactory theJSONLanguageFactory = (JSONLanguageFactory)EPackage.Registry.INSTANCE.getEFactory(JSONLanguagePackage.eNS_URI);
      if (theJSONLanguageFactory != null)
      {
        return theJSONLanguageFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new JSONLanguageFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JSONLanguageFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case JSONLanguagePackage.JSON_LANGUAGE: return createjSONLanguage();
      case JSONLanguagePackage.STATEMENT: return createStatement();
      case JSONLanguagePackage.VALUE: return createValue();
      case JSONLanguagePackage.ARRAY: return createArray();
      case JSONLanguagePackage.TEXT: return createText();
      case JSONLanguagePackage.BOOLEAN: return createBoolean();
      case JSONLanguagePackage.NULL: return createNull();
      case JSONLanguagePackage.NUMBER: return createNumber();
      case JSONLanguagePackage.INT_NUMBER: return createIntNumber();
      case JSONLanguagePackage.COMPLEX_NUMBER: return createComplexNumber();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public jSONLanguage createjSONLanguage()
  {
    jSONLanguageImpl jSONLanguage = new jSONLanguageImpl();
    return jSONLanguage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Statement createStatement()
  {
    StatementImpl statement = new StatementImpl();
    return statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Value createValue()
  {
    ValueImpl value = new ValueImpl();
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Array createArray()
  {
    ArrayImpl array = new ArrayImpl();
    return array;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Text createText()
  {
    TextImpl text = new TextImpl();
    return text;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public uk.kcl.ac.inf.jsonlang.jSONLanguage.Boolean createBoolean()
  {
    BooleanImpl boolean_ = new BooleanImpl();
    return boolean_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Null createNull()
  {
    NullImpl null_ = new NullImpl();
    return null_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public uk.kcl.ac.inf.jsonlang.jSONLanguage.Number createNumber()
  {
    NumberImpl number = new NumberImpl();
    return number;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntNumber createIntNumber()
  {
    IntNumberImpl intNumber = new IntNumberImpl();
    return intNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComplexNumber createComplexNumber()
  {
    ComplexNumberImpl complexNumber = new ComplexNumberImpl();
    return complexNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSONLanguagePackage getJSONLanguagePackage()
  {
    return (JSONLanguagePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static JSONLanguagePackage getPackage()
  {
    return JSONLanguagePackage.eINSTANCE;
  }

} //JSONLanguageFactoryImpl
