/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.jsonLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import uk.kcl.ac.inf.jsonlang.jsonLanguage.JsonLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NumberImpl extends ValueImpl implements uk.kcl.ac.inf.jsonlang.jsonLanguage.Number
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NumberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonLanguagePackage.Literals.NUMBER;
  }

} //NumberImpl
