/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.validation;

import uk.kcl.ac.inf.jsonlang.validation.AbstractJsonLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class JsonLanguageValidator extends AbstractJsonLanguageValidator {
}
