/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.validation;

import org.eclipse.xtext.validation.Check;
import uk.kcl.ac.inf.jsonlang.jSONLanguage.Statement;
import uk.kcl.ac.inf.jsonlang.validation.AbstractJSONLanguageValidator;

/**
 * This class contains custom validation rules.
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class JSONLanguageValidator extends AbstractJSONLanguageValidator {
  @Check
  public Object CheckKeyDoesNotStartWithNumber(final Statement statement) {
    return null;
  }
}
