/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.kcl.ac.inf.jsonlang.ui.internal.JsonlangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JSONLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(JsonlangActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		JsonlangActivator activator = JsonlangActivator.getInstance();
		return activator != null ? activator.getInjector(JsonlangActivator.UK_KCL_AC_INF_JSONLANG_JSONLANGUAGE) : null;
	}

}
