/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JSONLanguageRuntimeModule extends AbstractJSONLanguageRuntimeModule {
}
