/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JSONLanguageStandaloneSetup extends JSONLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new JSONLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
