/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JsonLanguageStandaloneSetup extends JsonLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new JsonLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
