/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.kcl.ac.inf.jsonlang.parser.antlr.internal.InternalJsonLanguageParser;
import uk.kcl.ac.inf.jsonlang.services.JsonLanguageGrammarAccess;

public class JsonLanguageParser extends AbstractAntlrParser {

	@Inject
	private JsonLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJsonLanguageParser createParser(XtextTokenStream stream) {
		return new InternalJsonLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JsonProgram";
	}

	public JsonLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JsonLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
