/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JSONLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uk/kcl/ac/inf/jsonlang/parser/antlr/internal/InternalJSONLanguage.tokens");
	}
}
