/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ide;

import uk.kcl.ac.inf.jsonlang.ide.AbstractJsonLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class JsonLanguageIdeModule extends AbstractJsonLanguageIdeModule {
}
