/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.kcl.ac.inf.jsonlang.JsonLanguageRuntimeModule;
import uk.kcl.ac.inf.jsonlang.JsonLanguageStandaloneSetup;
import uk.kcl.ac.inf.jsonlang.ide.JsonLanguageIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class JsonLanguageIdeSetup extends JsonLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    JsonLanguageRuntimeModule _jsonLanguageRuntimeModule = new JsonLanguageRuntimeModule();
    JsonLanguageIdeModule _jsonLanguageIdeModule = new JsonLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_jsonLanguageRuntimeModule, _jsonLanguageIdeModule));
  }
}
