/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.ac.inf.jsonlang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.kcl.ac.inf.jsonlang.JSONLanguageRuntimeModule;
import uk.kcl.ac.inf.jsonlang.JSONLanguageStandaloneSetup;
import uk.kcl.ac.inf.jsonlang.ide.JSONLanguageIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class JSONLanguageIdeSetup extends JSONLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    JSONLanguageRuntimeModule _jSONLanguageRuntimeModule = new JSONLanguageRuntimeModule();
    JSONLanguageIdeModule _jSONLanguageIdeModule = new JSONLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_jSONLanguageRuntimeModule, _jSONLanguageIdeModule));
  }
}
